dim_gnn: 128
n_gnn: 3
interaction_net: false
sphysnet_interaction_net: false
sphysnet_module: true
use_sphysnet_out: true
sphysnet_cutoff: 10.0
no_rotor_penalty: false
dropout_rate: 0.1
vdw_N: 6.0
max_vdw_interaction: 0.0356
min_vdw_interaction: 0.0178
lr: 0.0001
lr_decay: 1.0
lr_decay_period: 200.0
weight_decay: 0.0
scaling: 1.0
lattice_dim: 24.0
grid_rotation: false
swa_weight: null
ngpu: 0
restart_file: ""
save_dir: ./results_reproduce/lppdbbind_md3000
data_path: ./data # /ai/share/workspace/jhzhou/data/SiPobe_data
md_data_path: ./data # /ai/share/workspace/sxia/smart_logic_data
use_lp_pdbbind: true
use_generalset: true
batch_size: 2
num_workers: 12
num_epochs: 300
best_saving_epochs: 300
loss_der1_ratio: 0.0
loss_der2_ratio: 0.0
min_loss_der2: 0.0
dm_correction: true
dev_vdw_radius: 0.2
hbond_enhancement: true
hbond_enhancement_max_ratio: 4.0
hbond_enhancement_min_ratio: 0.5
use_md_data: true
use_md_rank_loss: false
loss_md_ratio: 0.25
static_sample_weight: 0.0
whole_traj_learning: true
rbf_sigmoid: false
freeze_non_rbf_layers: false
rbf_residual_weight: 0.1
rbf_pos_encoding_max_len: 500
rbf_num_heads: 16
n_total_frames: 50
model_weight_dir: ???
output_dir: AUTO
casf2016_val: false
lp_pdbbind_test: true
casf2016_coreset_path: /ai/share/workspace/jhzhou/data_LT/CASF-2016
target_file: null
reference_file: null
